# Generated by Django 2.1.7 on 2019-05-26 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='c_admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(blank=True, max_length=50, null=True)),
                ('d_name', models.CharField(blank=True, max_length=50, null=True)),
                ('admission', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('h_cut_off', models.FloatField(blank=True, null=True)),
                ('cut_off', models.FloatField(blank=True, null=True)),
                ('l_cut_off', models.FloatField(blank=True, null=True)),
                ('ad_info', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='c_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('c_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.c_admission')),
            ],
        ),
        migrations.CreateModel(
            name='chk_value',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('preferwhere1', models.CharField(blank=True, max_length=50, null=True)),
                ('preferwhere2', models.CharField(blank=True, max_length=50, null=True)),
                ('preferwhere3', models.CharField(blank=True, max_length=50, null=True)),
                ('prefertype1', models.CharField(blank=True, max_length=50, null=True)),
                ('prefertype2', models.CharField(blank=True, max_length=50, null=True)),
                ('prefertype3', models.CharField(blank=True, max_length=50, null=True)),
                ('prefertype4', models.CharField(blank=True, max_length=50, null=True)),
                ('prefertype5', models.CharField(blank=True, max_length=50, null=True)),
                ('prefertype6', models.CharField(blank=True, max_length=50, null=True)),
                ('total_avgrate', models.FloatField(blank=True, null=True)),
                ('main_avgrate', models.FloatField(blank=True, null=True)),
                ('executive_cnt', models.IntegerField(blank=True, null=True)),
                ('absent', models.IntegerField(blank=True, null=True)),
                ('award_cnt', models.IntegerField(blank=True, null=True)),
                ('circle_cnt', models.IntegerField(blank=True, null=True)),
                ('volunteer', models.IntegerField(blank=True, null=True)),
                ('reading', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='input_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('subject1', models.CharField(blank=True, max_length=50, null=True)),
                ('subject2', models.CharField(blank=True, max_length=50, null=True)),
                ('complete_unit', models.IntegerField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, max_length=1000)),
                ('hits', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='p_case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_num', models.IntegerField(blank=True, null=True)),
                ('volunteer', models.IntegerField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('president', models.IntegerField(blank=True, null=True)),
                ('absence', models.IntegerField(blank=True, null=True)),
                ('award', models.IntegerField(blank=True, null=True)),
                ('club', models.IntegerField(blank=True, null=True)),
                ('book_report', models.IntegerField(blank=True, null=True)),
                ('c_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.c_admission')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='SOME STRING', max_length=10)),
                ('sex', models.CharField(default='SOME STRING', max_length=10)),
                ('h_type', models.CharField(default='SOME STRING', max_length=10)),
                ('type', models.CharField(default='SOME STRING', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='search_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_type', models.CharField(blank=True, max_length=50, null=True)),
                ('c_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.c_admission')),
                ('ch_val', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chk_value')),
            ],
        ),
    ]
