# Generated by Django 2.1.7 on 2019-05-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_case',
            name='content',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
