# Generated by Django 2.1.7 on 2019-04-07 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190407_1643'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DjangoBoard',
            new_name='NoticeBoard',
        ),
    ]
