# Generated by Django 2.1.7 on 2019-04-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190414_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chk_value',
            name='prefertype7',
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='memo',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
