# Generated by Django 2.1.7 on 2019-05-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190512_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='c_admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(blank=True, max_length=50, null=True)),
                ('d_name', models.CharField(blank=True, max_length=50, null=True)),
                ('admission', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('cut_off', models.FloatField(blank=True, null=True)),
                ('ad_info', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
