# Generated by Django 2.1.7 on 2019-05-12 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_c_info_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='p_case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_num', models.IntegerField(blank=True, null=True)),
                ('volunteer', models.IntegerField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('president', models.IntegerField(blank=True, null=True)),
                ('absence', models.IntegerField(blank=True, null=True)),
                ('award', models.IntegerField(blank=True, null=True)),
                ('club', models.IntegerField(blank=True, null=True)),
                ('book_report', models.IntegerField(blank=True, null=True)),
                ('c_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.c_admission')),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
