# Generated by Django 2.1.7 on 2019-05-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_chk_value_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chk_value',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
