# Generated by Django 2.1.7 on 2019-05-12 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_search_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search_history',
            old_name='C_name',
            new_name='c_name',
        ),
    ]
