# Generated by Django 2.1.7 on 2019-05-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190512_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_admission',
            name='h_cut_off',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='c_admission',
            name='l_cut_off',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
