# Generated by Django 2.1.7 on 2019-05-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190519_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(default='SOME STRING', max_length=10),
        ),
    ]
