# Generated by Django 2.1.7 on 2019-05-19 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_profile_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='area',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phonenum',
        ),
    ]
