# Generated by Django 2.1.7 on 2019-05-26 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20190520_0211'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='c_admission',
            unique_together={('c_name', 'd_name', 'admission', 'year')},
        ),
    ]
