# Generated by Django 2.1.7 on 2019-05-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190526_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_admission',
            name='d_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='c_admission',
            unique_together={('c_name', 'd_type', 'd_name', 'admission', 'year')},
        ),
    ]
